language: node_js

node_js: '8'

cache: yarn

addons:
  sonarcloud:
    organization: "proustibat-github"
    token:
      secure: "0.............="

install:
  - yarn install

script:
  - yarn build
  - sonar-scanner
