language: php

node_js: '8'
cache: yarn

install:
  - yarn install

php:
  - 7.0

env:
  - DB=mysql

addons:
  sonarcloud:
    organization: "utopszkij-github"

script: 
  - yarn build
  - tests/test.sh
  - sonar-scanner

